ServerEvents.tags('block', event => {
    // Deep Void Ores to Divination Rods
    event.add('theurgy:divination_rod_t4_allowed_blocks', 'the_deep_void:onyx_ore')
    event.add('theurgy:divination_rod_t4_allowed_blocks', 'the_deep_void:lavendite_ore')
    event.add('theurgy:divination_rod_t4_allowed_blocks', 'the_deep_void:sulfur_ore')
    event.add('theurgy:divination_rod_t4_allowed_blocks', 'the_deep_void:cinnabar_ore')
    event.add('theurgy:divination_rod_t4_allowed_blocks', 'the_deep_void:grim_soil')
    event.add('theurgy:divination_rod_t4_allowed_blocks', 'the_deep_void:fossilized_flesh')
    event.add('theurgy:divination_rod_t4_allowed_blocks', 'the_deep_void:regurgitated_matter')
    event.add('theurgy:divination_rod_t4_allowed_blocks', 'the_deep_void:bismuth_ore')
    event.add('theurgy:divination_rod_t4_allowed_blocks', 'the_deep_void:voidrium_ore')

    event.add('theurgy:divination_rod_t3_allowed_blocks', 'the_deep_void:onyx_ore')
    event.add('theurgy:divination_rod_t3_allowed_blocks', 'the_deep_void:lavendite_ore')
    event.add('theurgy:divination_rod_t3_allowed_blocks', 'the_deep_void:sulfur_ore')
    event.add('theurgy:divination_rod_t3_allowed_blocks', 'the_deep_void:cinnabar_ore')
    event.add('theurgy:divination_rod_t3_allowed_blocks', 'the_deep_void:grim_soil')
    event.add('theurgy:divination_rod_t3_allowed_blocks', 'the_deep_void:fossilized_flesh')
    event.add('theurgy:divination_rod_t3_allowed_blocks', 'the_deep_void:regurgitated_matter')
    event.add('theurgy:divination_rod_t3_allowed_blocks', 'the_deep_void:bismuth_ore')

    event.add('theurgy:divination_rod_t2_allowed_blocks', 'the_deep_void:onyx_ore')
    event.add('theurgy:divination_rod_t2_allowed_blocks', 'the_deep_void:lavendite_ore')
    event.add('theurgy:divination_rod_t2_allowed_blocks', 'the_deep_void:sulfur_ore')
    event.add('theurgy:divination_rod_t2_allowed_blocks', 'the_deep_void:cinnabar_ore')
    event.add('theurgy:divination_rod_t2_allowed_blocks', 'the_deep_void:grim_soil')

    event.add('theurgy:divination_rod_t1_allowed_blocks', 'the_deep_void:onyx_ore')
    event.add('theurgy:divination_rod_t1_allowed_blocks', 'the_deep_void:lavendite_ore')
})