// StartupEvents.registry('item', (event) => {
// 	// event.create('alchemical_sulfur_ancient_onyx', 'theurgy:alchemical_sulfur')
//     //     .tag('theurgy:alchemical_sulfurs')
// 	// 	.sourceItem('the_deep_void:ancient_onyx')
// 	// 	.sourceName("Ancient Onyx")
// 	// 	.sulfurTier("precious")
// 	// 	.sulfurType("gems")
//     // event.create('alchemical_sulfur_grim_shard', 'theurgy:alchemical_sulfur')
//     //     .tag('theurgy:alchemical_sulfurs')
// 	// 	.sourceItem('the_deep_void:grim_shard')
// 	// 	.sourceName("Grim Shard")
// 	// 	.sulfurTier("rare")
// 	// 	.sulfurType("other minerals")
// })
// StartupEvents.registry('item', (event) => {
//     event.create('alchemical_sulfur_glowstone', 'theurgy:alchemical_sulfur')
//         .tag('theurgy:alchemical_sulfurs')
//         .sourceItem('minecraft:glowstone')
//         .sourceName("Glowstone")
//         .sulfurTier("common")
//         .sulfurType("other_minerals")
// })
// StartupEvents.registry('item', (event) => {
//     event.create('alchemical_sulfur_glowstone', 'theurgy:alchemical_sulfur')
//         .tag('theurgy:alchemical_sulfurs')
//         .sourceItem('minecraft:glowstone')
//         .sourceName("Glowstone")
//         .sulfurTier("common")
//         .sulfurType("other_minerals")
// })